name: Cypress Tests

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run hugo build
        uses: jakejarvis/hugo-build-action@master 
        with:
          args: --gc --config ./config.toml
      - name: run server
        run: |
          cd public && python -m http.server 1313 &
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: test
          browser: chrome
      - name: Save screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: test/cypress/screenshots/
      - name: Upload Screenshots
        uses: edunad/actions-image@v1.0.1
        with:
            path: './test/cypress/screenshots/*.png'
            GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
